/*
 * AUTO-GENERATED semantic relation map.
 *
 * Source: canonical published symbol corpus.
 * Strategy: conservative parent/variant relationships.
 * Ambiguous multi-parent compounds, sibling meshes, and
 * low-confidence lexical matches are excluded.
 *
 * Do not edit individual relations here manually.
 */

export const generatedRelatedSymbolSlugs: Readonly<
  Record<string, readonly string[]>
> = {
  "aci-biber": ["biber"],
  "akan-dere": ["dere"],
  "akraba": ["olmus-akraba", "anne-tarafi-akraba"],
  "aldatmak": ["sevgilini-aldatmak"],
  "altin": ["altin-bulmak"],
  "altin-bulmak": ["altin"],
  "alyans": ["alyans-takmak"],
  "alyans-takmak": ["alyans"],
  "anahtar": ["anahtar-bulmak", "anahtar-kaybetmek", "elimde-anahtar"],
  "anahtar-bulmak": ["anahtar"],
  "anahtar-kaybetmek": ["anahtar"],
  "anahtarla-kapi-acmak": ["kapi"],
  "anne": ["olmus-anne"],
  "anne-tarafi-akraba": ["akraba"],
  "araba": ["araba-anahtari", "araba-kazasi", "araba-kullanmak", "araba-satmak"],
  "araba-anahtari": ["araba"],
  "araba-kazasi": ["araba"],
  "araba-kullanmak": ["araba"],
  "araba-satmak": ["araba"],
  "ari": ["ari-kovani"],
  "ari-kovani": ["ari"],
  "aslan": ["aslan-yavrusu"],
  "aslan-yavrusu": ["aslan"],
  "aslandan-kacmak": ["kacmak"],
  "at": ["at-arabasi"],
  "at-arabasi": ["at"],
  "ates": ["ates-sondurmek"],
  "ates-sondurmek": ["ates"],
  "ay": ["ay-tutulmasi"],
  "ay-tutulmasi": ["ay"],
  "ayakkabi": ["ayakkabi-aramak", "ayakkabi-denemek", "ayakkabi-giymek", "eski-ayakkabi"],
  "ayakkabi-aramak": ["ayakkabi"],
  "ayakkabi-denemek": ["ayakkabi"],
  "ayakkabi-giymek": ["ayakkabi"],
  "ayi": ["ayi-yavrusu", "beyaz-ayi", "kahverengi-ayi", "siyah-ayi"],
  "ayi-yavrusu": ["ayi"],
  "ayna": ["ayna-kirilmasi"],
  "ayna-kirilmasi": ["ayna"],
  "baba": ["olmus-baba", "vefat-eden-baba"],
  "baklava": ["baklava-yapmak"],
  "baklava-yapmak": ["baklava"],
  "balik": ["balik-yemek"],
  "balik-yemek": ["balik"],
  "bardak": ["cam-bardak"],
  "bebek": ["bebek-arabasi", "bebek-oyuncak", "bebek-uyutmak", "kundaktaki-bebek"],
  "bebek-arabasi": ["bebek"],
  "bebek-oyuncak": ["bebek"],
  "bebek-uyutmak": ["bebek"],
  "bembeyaz-kar": ["kar"],
  "berrak-deniz": ["deniz"],
  "beyaz-ayi": ["ayi"],
  "beyaz-dut": ["dut"],
  "beyaz-gelinlik": ["gelinlik"],
  "beyaz-gul": ["gul"],
  "beyaz-kar": ["kar"],
  "beyaz-koyun": ["koyun"],
  "beyaz-lahana": ["lahana"],
  "beyaz-mantar": ["mantar"],
  "beyaz-perde": ["perde"],
  "beyaz-tavuk": ["tavuk"],
  "beyaz-uzum": ["uzum"],
  "biber": ["biber-dolmasi", "biber-toplamak", "aci-biber", "dolma-biber"],
  "biber-dolmasi": ["biber"],
  "biber-toplamak": ["biber"],
  "birilerinden-kacmak-ve-kovalanmak": ["kovalanmak"],
  "bomba": ["bomba-patlamasi"],
  "bomba-patlamasi": ["bomba"],
  "borek": ["borek-yapmak"],
  "borek-yapmak": ["borek"],
  "bozuk-yumurta": ["yumurta"],
  "burundan-kan-gelmesi": ["kan"],
  "buyu": ["buyu-yapilmasi"],
  "buyu-yapilmasi": ["buyu"],
  "buyuk-deprem": ["deprem"],
  "buyuk-kopek": ["kopek"],
  "cam-bardak": ["bardak"],
  "camurlu-su": ["su"],
  "canli-tavuk": ["tavuk"],
  "canta": ["canta-tasimak"],
  "canta-tasimak": ["canta"],
  "cenaze": ["cenaze-arabasi", "cenaze-evi"],
  "cenaze-arabasi": ["cenaze"],
  "cenaze-evi": ["cenaze"],
  "cicek": ["cicek-dikmek", "cicek-ekmek", "cicek-sulamak", "cicek-toplamak"],
  "cicek-dikmek": ["cicek"],
  "cicek-ekmek": ["cicek"],
  "cicek-sulamak": ["cicek"],
  "cicek-toplamak": ["cicek"],
  "cig-hamur": ["hamur"],
  "cig-kofte": ["kofte"],
  "cig-yumurta": ["yumurta"],
  "cikolata": ["cikolata-almak"],
  "cikolata-almak": ["cikolata"],
  "cilek": ["cilek-toplamak"],
  "cilek-toplamak": ["cilek"],
  "cocuk": ["cocuk-bakmak", "cocuk-sevmek", "erkek-cocuk-sevmek"],
  "cocuk-bakmak": ["cocuk"],
  "cocuk-sevmek": ["cocuk"],
  "cok-kedi": ["kedi"],
  "cok-su-icmek": ["su"],
  "dans": ["dans-etmek"],
  "dans-etmek": ["dans"],
  "define": ["define-aramak"],
  "define-aramak": ["define"],
  "deniz": ["deniz-dalgasi", "berrak-deniz", "masmavi-deniz"],
  "deniz-dalgasi": ["deniz"],
  "deprem": ["buyuk-deprem", "evde-deprem"],
  "depreme-yakalanmak": ["yakalanmak"],
  "dere": ["akan-dere"],
  "dis": ["dis-cekmek", "dis-curumesi", "dis-dokulmesi", "dis-fircalamak"],
  "dis-cekmek": ["dis"],
  "dis-curumesi": ["dis"],
  "dis-dokulmesi": ["dis"],
  "dis-fircalamak": ["dis"],
  "dogum": ["dogum-gunu"],
  "dogum-gunu": ["dogum"],
  "dolma-biber": ["biber"],
  "domuz": ["domuz-eti", "domuz-surusu", "domuz-yavrusu"],
  "domuz-eti": ["domuz"],
  "domuz-surusu": ["domuz"],
  "domuz-yavrusu": ["domuz"],
  "dua": ["dua-okumak"],
  "dua-okumak": ["dua"],
  "dusmek": ["ucurumdan-dusmek", "yuksekten-dusmek"],
  "dut": ["dut-agaci", "dut-toplamak", "beyaz-dut"],
  "dut-agaci": ["dut"],
  "dut-toplamak": ["dut"],
  "elektrikli-supurge": ["supurge"],
  "elimde-anahtar": ["anahtar"],
  "elinde-silah": ["silah"],
  "erkek-cocuk-sevmek": ["cocuk"],
  "eski-ayakkabi": ["ayakkabi"],
  "eski-kaynana": ["kaynana"],
  "eski-sevgili": ["sevgili"],
  "eski-sevgiliyle-evlenmek": ["evlenmek"],
  "ev": ["ev-anahtari", "ev-bakmak", "ev-gezmek", "ev-yapmak"],
  "ev-anahtari": ["ev"],
  "ev-bakmak": ["ev"],
  "ev-gezmek": ["ev"],
  "ev-yapmak": ["ev"],
  "evde-deprem": ["deprem"],
  "eve-fare-girmesi": ["fare"],
  "eve-su-basmasi": ["su"],
  "evlenmek": ["eski-sevgiliyle-evlenmek"],
  "fare": ["fare-kovalamak", "fare-yakalamak", "fare-yavrusu", "eve-fare-girmesi"],
  "fare-kovalamak": ["fare"],
  "fare-yakalamak": ["fare"],
  "fare-yavrusu": ["fare"],
  "fasulye": ["kuru-fasulye"],
  "fotograf": ["fotograf-cekmek"],
  "fotograf-cekmek": ["fotograf"],
  "futbol": ["futbol-oynamak"],
  "futbol-oynamak": ["futbol"],
  "gelin": ["gelin-olmak"],
  "gelin-olmak": ["gelin"],
  "gelinlik": ["gelinlik-giymek", "beyaz-gelinlik"],
  "gelinlik-giymek": ["gelinlik"],
  "gozluk": ["gozluk-takmak"],
  "gozluk-takmak": ["gozluk"],
  "gri-kedi": ["kedi"],
  "gul": ["beyaz-gul", "pembe-gul"],
  "gunduz": ["gunduz-dus-kurmak"],
  "gunduz-dus-kurmak": ["gunduz"],
  "gunes": ["gunes-tutulmasi"],
  "gunes-tutulmasi": ["gunes"],
  "halay": ["halay-cekenleri"],
  "halay-cekenleri": ["halay"],
  "hali": ["hali-almak", "hali-yikamak"],
  "hali-almak": ["hali"],
  "hali-yikamak": ["hali"],
  "hamur": ["cig-hamur"],
  "hastane": ["hastane-yatagi"],
  "hastane-yatagi": ["hastane"],
  "havada-ucmak": ["ucmak"],
  "helva": ["helva-yapmak"],
  "helva-yapmak": ["helva"],
  "icli-kofte": ["kofte"],
  "igne": ["toplu-igne"],
  "incir": ["incir-agaci", "kuru-incir"],
  "incir-agaci": ["incir"],
  "inek": ["inek-surusu", "siyah-inek"],
  "inek-surusu": ["inek"],
  "internet": ["internet-sitesi"],
  "internet-sitesi": ["internet"],
  "ip": ["ip-kopmasi"],
  "ip-kopmasi": ["ip"],
  "kacmak": ["aslandan-kacmak", "yangindan-kacmak"],
  "kahve": ["kahve-fincani"],
  "kahve-fincani": ["kahve"],
  "kahverengi-ayi": ["ayi"],
  "kalp": ["kalp-krizi-gecirmek"],
  "kalp-krizi-gecirmek": ["kalp"],
  "kan": ["kan-tukurmek", "kan-vermek", "burundan-kan-gelmesi"],
  "kan-tukurmek": ["kan"],
  "kan-vermek": ["kan"],
  "kapi": ["kapi-acmak", "kilitli-kapi", "anahtarla-kapi-acmak"],
  "kapi-acmak": ["kapi"],
  "kar": ["bembeyaz-kar", "beyaz-kar", "yerde-kar"],
  "kara-lahana": ["lahana"],
  "kara-sinek": ["sinek"],
  "kara-uzum": ["uzum"],
  "karpuz": ["karpuz-tarlasi"],
  "karpuz-tarlasi": ["karpuz"],
  "kaynana": ["eski-kaynana"],
  "keci": ["siyah-keci"],
  "kedi": ["kedi-beslemek", "kedi-kovmak", "cok-kedi", "gri-kedi"],
  "kedi-beslemek": ["kedi"],
  "kedi-kovmak": ["kedi"],
  "kendini-olu-gormek": ["olu"],
  "kilitli-kapi": ["kapi"],
  "kofte": ["cig-kofte", "icli-kofte"],
  "konusmak": ["telefonla-konusmak"],
  "kopek": ["kopek-havlamasi", "kopek-sahiplenmek", "kopek-surusu", "buyuk-kopek"],
  "kopek-havlamasi": ["kopek"],
  "kopek-sahiplenmek": ["kopek"],
  "kopek-surusu": ["kopek"],
  "kovalanmak": ["birilerinden-kacmak-ve-kovalanmak"],
  "koyun": ["beyaz-koyun"],
  "kulak": ["kulak-deldirmek", "kulak-kiri"],
  "kulak-deldirmek": ["kulak"],
  "kulak-kiri": ["kulak"],
  "kundaktaki-bebek": ["bebek"],
  "kupe": ["kupe-takmak"],
  "kupe-takmak": ["kupe"],
  "kuru-fasulye": ["fasulye"],
  "kuru-incir": ["incir"],
  "lahana": ["lahana-sarmasi", "beyaz-lahana", "kara-lahana"],
  "lahana-sarmasi": ["lahana"],
  "limon": ["limon-toplamak"],
  "limon-toplamak": ["limon"],
  "mantar": ["beyaz-mantar"],
  "manti": ["manti-yapmak"],
  "manti-yapmak": ["manti"],
  "masmavi-deniz": ["deniz"],
  "melek": ["melek-gormek"],
  "melek-gormek": ["melek"],
  "mercimek": ["mercimek-corbasi"],
  "mercimek-corbasi": ["mercimek"],
  "mesaj": ["mesaj-almak"],
  "mesaj-almak": ["mesaj"],
  "mezar": ["mezar-kazmak"],
  "mezar-kazmak": ["mezar"],
  "odun": ["odun-toplamak"],
  "odun-toplamak": ["odun"],
  "olmus-akraba": ["akraba"],
  "olmus-anne": ["anne"],
  "olmus-baba": ["baba"],
  "olu": ["olu-dirilmesi", "olu-insanlar", "kendini-olu-gormek"],
  "olu-dirilmesi": ["olu"],
  "olu-insanlar": ["olu"],
  "otobus": ["otobus-kullanmak"],
  "otobus-kullanmak": ["otobus"],
  "pamuk": ["pamuk-toplamak"],
  "pamuk-toplamak": ["pamuk"],
  "parmak": ["parmak-kopmasi"],
  "parmak-kopmasi": ["parmak"],
  "parmakta-yuzuk": ["yuzuk"],
  "pasta": ["pasta-yapmak"],
  "pasta-yapmak": ["pasta"],
  "patates": ["patates-soymak"],
  "patates-soymak": ["patates"],
  "pembe-gul": ["gul"],
  "perde": ["beyaz-perde", "tul-perde"],
  "saat": ["saat-takmak"],
  "saat-takmak": ["saat"],
  "sac": ["sac-boyamak", "sac-dokulmesi", "sac-kesmek", "sac-uzamasi"],
  "sac-boyamak": ["sac"],
  "sac-dokulmesi": ["sac"],
  "sac-kesmek": ["sac"],
  "sac-uzamasi": ["sac"],
  "sevgili": ["sevgili-edinmek", "sevgili-olmak", "eski-sevgili"],
  "sevgili-edinmek": ["sevgili"],
  "sevgili-olmak": ["sevgili"],
  "sevgilini-aldatmak": ["aldatmak"],
  "silah": ["elinde-silah"],
  "sinek": ["kara-sinek"],
  "siyah-ayi": ["ayi"],
  "siyah-inek": ["inek"],
  "siyah-keci": ["keci"],
  "su": ["su-icmek", "camurlu-su", "cok-su-icmek", "eve-su-basmasi"],
  "su-icmek": ["su"],
  "supurge": ["elektrikli-supurge"],
  "sut": ["sut-almak"],
  "sut-almak": ["sut"],
  "tarla": ["tarla-almak"],
  "tarla-almak": ["tarla"],
  "tavuk": ["tavuk-eti", "tavuk-yumurtasi", "beyaz-tavuk", "canli-tavuk"],
  "tavuk-eti": ["tavuk"],
  "tavuk-yumurtasi": ["tavuk"],
  "telefon": ["telefon-almak", "telefon-kirilmasi", "yeni-telefon-almak"],
  "telefon-almak": ["telefon"],
  "telefon-kirilmasi": ["telefon"],
  "telefonla-konusmak": ["konusmak"],
  "tesbih": ["tesbih-cekmek"],
  "tesbih-cekmek": ["tesbih"],
  "tirnak": ["tirnak-kesmek"],
  "tirnak-kesmek": ["tirnak"],
  "toplu-igne": ["igne"],
  "tren": ["tren-kazasi"],
  "tren-kazasi": ["tren"],
  "tul-perde": ["perde"],
  "ucak": ["ucak-kazasi"],
  "ucak-kazasi": ["ucak"],
  "ucmak": ["havada-ucmak"],
  "ucurumdan-dusmek": ["dusmek"],
  "uzum": ["uzum-yemek", "beyaz-uzum", "kara-uzum"],
  "uzum-yemek": ["uzum"],
  "vefat-eden-baba": ["baba"],
  "vucudunda-yara": ["yara"],
  "yakalanmak": ["depreme-yakalanmak"],
  "yangin": ["yangin-sondurmek"],
  "yangin-sondurmek": ["yangin"],
  "yangindan-kacmak": ["kacmak"],
  "yara": ["vucudunda-yara"],
  "yatak": ["yatak-odasi"],
  "yatak-odasi": ["yatak"],
  "yeni-telefon-almak": ["telefon"],
  "yerde-kar": ["kar"],
  "yufka": ["yufka-acmak", "yufka-ekmek-yapmak"],
  "yufka-acmak": ["yufka"],
  "yufka-ekmek-yapmak": ["yufka"],
  "yuksekten-dusmek": ["dusmek"],
  "yumurta": ["bozuk-yumurta", "cig-yumurta"],
  "yuzuk": ["yuzuk-takmak", "parmakta-yuzuk"],
  "yuzuk-takmak": ["yuzuk"],
  "zincir": ["zincir-kirilmasi"],
  "zincir-kirilmasi": ["zincir"],
};
