/**
 * INUS — Next Generation Dream Symbol Content Schema
 *
 * Bu dosya mevcut DreamSymbol yapısının yerine geçmez.
 * Yeni sembol üretim pipeline'ının "yayınlanabilir içerik sözleşmesidir".
 *
 * Pipeline:
 * Research → Generation → Critique → Revision → Turkish QA → Final QA
 */

export type SymbolContentQuality = {
  score: number;
  passed: boolean;
  issues: string[];
};

export type SymbolSource = {
  author?: string;
  title: string;
  publication?: string;
  year?: number;
  url?: string;
  relevance: string;
};

/**
 * Internal research source.
 *
 * `id` exists only inside the research/evidence package so that
 * individual research claims can point to grounded sources.
 * It is not part of the public SymbolContent source contract.
 */
export type SymbolResearchSource = SymbolSource & {
  id: string;
};

/**
 * An evidence-bearing research statement.
 *
 * Every claim must identify the grounded research sources that
 * support it. Claims that lose all grounded source references
 * during reconciliation are removed before generation.
 */
export type SymbolResearchClaim = {
  text: string;
  sourceIds: string[];
};

export type SymbolVariation = {
  title: string;
  description: string;
};

export type SymbolFaq = {
  question: string;
  answer: string;
};

export type SymbolComparison = {
  approach: string;
  interpretation: string;
  evidenceLevel:
    | "research"
    | "theoretical"
    | "traditional"
    | "spiritual";
};

export type SymbolContent = {
  /**
   * Identity
   */
  slug: string;
  title: string;

  /**
   * Search / introduction
   *
   * Must be specific to this symbol.
   * No generic "farklı duygusal, psikolojik..." templates.
   */
  shortDescription: string;

  /**
   * Symbol-specific associations
   */
  positiveAssociations: string[];
  challengingAssociations: string[];
  contextDependentAssociations: string[];

  /**
   * Concrete dream manifestations.
   *
   * These are not generic variations generated by a template.
   */
  commonVariations: SymbolVariation[];

  /**
   * Evidence-based psychological perspective
   */
  psychology: string;

  /**
   * Jungian interpretation
   */
  jungian: string;

  /**
   * Cultural / religious traditions
   */
  islamicTradition: string;
  christianTraditions: string;
  jewishTraditions: string;
  buddhistEasternApproaches: string;
  spiritualApproaches: string;

  /**
   * Comparative synthesis
   */
  comparisonTable: SymbolComparison[];
  commonGround: string;
  differences: string;

  /**
   * INUS-specific editorial assessment.
   *
   * This must explain how INUS approaches this symbol,
   * rather than repeat the general sections.
   */
  inusAssessment: string;

  /**
   * Frequently asked questions.
   *
   * Questions must arise naturally from this symbol.
   */
  faq: SymbolFaq[];

  /**
   * Sources actually relevant to this symbol.
   */
  sources: SymbolSource[];

  /**
   * Semantic relationships.
   *
   * These are determined after content generation,
   * not by superficial word overlap alone.
   */
  relatedSlugs: string[];

};

/**
 * Research package consumed by the content-generation agent.
 */
export type SymbolResearch = {
  symbol: string;
  coreConcepts: string[];

  /**
   * Empirical / scientific psychology only.
   *
   * Psychoanalytic theory and historical symbolism do not
   * belong in this field.
   */
  psychologicalResearch: SymbolResearchClaim[];

  /**
   * Freud, classical psychoanalysis and related
   * psychodynamic theoretical material.
   */
  psychoanalyticMaterial: SymbolResearchClaim[];

  /**
   * Jung / analytical psychology.
   */
  jungianMaterial: SymbolResearchClaim[];

  /**
   * Academic historical, iconographic or cultural-symbolic
   * material that is neither empirical psychology nor a
   * religious/traditional interpretation.
   */
  historicalCulturalMaterial: SymbolResearchClaim[];

  islamicMaterial: SymbolResearchClaim[];
  christianMaterial: SymbolResearchClaim[];
  jewishMaterial: SymbolResearchClaim[];
  buddhistEasternMaterial: SymbolResearchClaim[];
  spiritualMaterial: SymbolResearchClaim[];

  relevantSources: SymbolResearchSource[];

  cautions: string[];
};

/**
 * Critic output.
 *
 * The critic does not rewrite the content.
 * It identifies what must be fixed.
 */
export type SymbolCritique = {
  overallScore: number;
  passed: boolean;

  genericity: {
    score: number;
    problems: string[];
  };

  repetition: {
    score: number;
    problems: string[];
  };

  factualReliability: {
    score: number;
    problems: string[];
  };

  symbolSpecificity: {
    score: number;
    problems: string[];
  };

  turkishQuality: {
    score: number;
    problems: string[];
  };

  sectionQuality: {
    score: number;
    problems: string[];
  };

  requiredChanges: string[];
};

/**
 * Final Turkish QA result.
 *
 * This stage happens AFTER revision.
 */
export type TurkishQaResult = {
  score: number;
  passed: boolean;

  grammarIssues: string[];
  morphologyIssues: string[];
  unnaturalPhrases: string[];
  translationLikePhrases: string[];
  repetitionIssues: string[];
  punctuationIssues: string[];
  terminologyIssues: string[];
  suggestedRevisions: string[];
};

/**
 * Final publication gate.
 */
export type FinalQaResult = {
  passed: boolean;
  score: number;

  blockers: string[];

  checks: {
    complete: boolean;
    symbolSpecific: boolean;
    nonGeneric: boolean;
    nonRepetitive: boolean;
    turkishNatural: boolean;
    sourceGrounded: boolean;
    jungianResponsible: boolean;
    religiouslyResponsible: boolean;
    seoNatural: boolean;
  };
};

/**
 * Complete pipeline artifact.
 *
 * This is what will eventually allow us to generate
 * thousands of symbols deterministically through the same
 * quality-controlled process.
 */
export type SymbolPipelineArtifact = {
  research: SymbolResearch;
  generatedContent: SymbolContent;
  critique: SymbolCritique;
  revision: SymbolContent | null;
  content: SymbolContent;

  quality: {
    critique: SymbolContentQuality;
    turkishQa: SymbolContentQuality;
    finalQa: SymbolContentQuality;
  };

  turkishQa: TurkishQaResult;
  finalQa: FinalQaResult;

  pipeline: {
    version: string;
    completedStages: string[];
    revisionApplied: boolean;
    publicationApproved: boolean;
  };

  generatedAt: string;
};
